### ISSUE TITLE
Error when trying to execute the latest version

### ISSUE THREAD

**Issue by Waskind** [flightcrank/JRatioBoost#5]
When I try to execute the file on terminal it shows me this and then nothing happens, the app doesn't load:

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at JRatioBoost.<init>(JRatioBoost.java:37)
        at JRatioBoost$9.run(JRatioBoost.java:664)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

I'm using Manjaro, Kernel version 5.8.18-1.

![Screenshot_20201222_144419](https://user-images.githubusercontent.com/49253564/102917558-34e87500-4464-11eb-8032-7fb025b05624.png)

**Comment by flightcrank** [comment]
My bad. It did work if you passed a torrent file form the command line as an argument. But didn't work if you didn't pass one in. I updated both the code and the .jar file to fix this. It should work fine now

I see your using KDE like i am. If your right click on the .jar file and tick the check box "make this executable" you should be able to just click the jar file from the file browser and have it work rather than having to run it from the command line. In any event, it should work fine now. 

Ill leave this issue open for a while incase you encounter any more problems

**Comment by Waskind** [comment]
It's working fine now. Thank you and thanks for the tip.
